[project]
name = "duckdb-changelog"
version = "0.1.0"
description = "Generate a single-file changelog of all DuckDB's releases"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[project.scripts]
fetch-changelog = "fetch_changelog:main"
check-updates = "check_and_update:main"
